2025-04-01 13:02:39,414 - ERROR - 'NoneType' object has no attribute 'strip'
2025-04-01 13:35:26,501 - ERROR - Erro ao processar e-mail: 'str' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 54, in <module>
    values = [match.group(1).strip() for match in re.findall(standard_result, result_body)]
              ^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'group'
2025-04-02 07:28:48,072 - INFO - Padrão de assunto do e-mail não encontrado
2025-04-02 07:28:48,099 - INFO - Padrão de assunto do e-mail não encontrado
2025-04-02 07:32:38,379 - INFO - Padrão de assunto do e-mail não encontrado
2025-04-02 07:32:38,404 - INFO - Padrão de assunto do e-mail não encontrado
2025-04-02 07:45:37,010 - ERROR - Erro no processamento dos e-mails: name 'sender' is not defined
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 40, in <module>
    and sender == 'NoReply.Workon@bosch.com'
       ^^^^^^
NameError: name 'sender' is not defined
2025-04-02 08:21:56,880 - ERROR - Erro geral: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KRP1PO\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 28, in <module>
    df = pd.read_excel(file, sheet_name=sheet)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\compat\_optional.py", line 138, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
2025-04-02 08:22:31,365 - ERROR - Erro geral: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KRP1PO\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 28, in <module>
    df = pd.read_excel(file, sheet_name=sheet)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\compat\_optional.py", line 138, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
2025-04-02 08:24:46,112 - ERROR - Erro geral: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KRP1PO\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\teste1.py", line 28, in <module>
    df = pd.read_excel(df_path, sheet_name=sheet_name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\compat\_optional.py", line 138, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
2025-04-02 08:27:14,693 - ERROR - Erro geral: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\compat\_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KRP1PO\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 26, in <module>
    df = pd.read_excel(file, sheet_name=sheet)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_base.py", line 1567, in __init__
    self._reader = self._engines[engine](
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\io\excel\_openpyxl.py", line 552, in __init__
    import_optional_dependency("openpyxl")
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\compat\_optional.py", line 138, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
2025-04-02 08:28:25,027 - ERROR - Erro geral: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
2025-04-02 08:33:56,380 - ERROR - Erro ao processar e-mail: 'A'
Traceback (most recent call last):
  File "C:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 65, in <module>
    empty_line_sheet = df[df['A'].isna()].index.min()
                          ~~^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\core\indexes\range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'A'
2025-04-02 08:37:10,054 - ERROR - Erro ao processar e-mail: 'A'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'A'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 67, in <module>
    empty_line_sheet = df[df['A'].isna()].index.min()
                          ~~^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'A'
2025-04-02 08:37:10,121 - ERROR - Erro ao processar e-mail: 'A'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'A'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 67, in <module>
    empty_line_sheet = df[df['A'].isna()].index.min()
                          ~~^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'A'
2025-04-02 08:37:10,168 - ERROR - Erro ao processar e-mail: 'A'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'A'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 67, in <module>
    empty_line_sheet = df[df['A'].isna()].index.min()
                          ~~^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'A'
2025-04-02 08:59:01,613 - INFO - Padrão de assunto do e-mail não encontrado
2025-04-02 08:59:01,628 - INFO - Padrão de assunto do e-mail não encontrado
2025-04-02 08:59:01,642 - INFO - Padrão de assunto do e-mail não encontrado
2025-04-02 09:01:28,911 - INFO - Padrão de assunto do e-mail não encontrado
2025-04-02 09:01:28,939 - INFO - Padrão de assunto do e-mail não encontrado
2025-04-02 09:01:28,955 - INFO - Padrão de assunto do e-mail não encontrado
2025-04-02 10:01:57,552 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: Workbook.save() missing 1 required positional argument: 'filename'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 76, in <module>
    file.save()
TypeError: Workbook.save() missing 1 required positional argument: 'filename'
2025-04-02 10:01:57,574 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: Workbook.save() missing 1 required positional argument: 'filename'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 76, in <module>
    file.save()
TypeError: Workbook.save() missing 1 required positional argument: 'filename'
2025-04-02 10:01:57,595 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: Workbook.save() missing 1 required positional argument: 'filename'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 76, in <module>
    file.save()
TypeError: Workbook.save() missing 1 required positional argument: 'filename'
2025-04-02 10:01:57,649 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: Workbook.save() missing 1 required positional argument: 'filename'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 76, in <module>
    file.save()
TypeError: Workbook.save() missing 1 required positional argument: 'filename'
2025-04-02 10:01:57,669 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: Workbook.save() missing 1 required positional argument: 'filename'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 76, in <module>
    file.save()
TypeError: Workbook.save() missing 1 required positional argument: 'filename'
2025-04-02 10:01:57,688 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: Workbook.save() missing 1 required positional argument: 'filename'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 76, in <module>
    file.save()
TypeError: Workbook.save() missing 1 required positional argument: 'filename'
2025-04-02 10:26:46,577 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:26:46,602 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:26:46,620 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:26:46,647 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:26:46,711 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:26:46,729 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:26:46,746 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:27:14,418 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:27:14,433 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:27:14,450 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:27:14,468 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:27:14,508 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:27:14,523 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 10:27:14,541 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: '<' not supported between instances of 'builtin_function_or_method' and 'int'
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 69, in <module>
    select_sheet.cell(row=next, column=col, value=value)
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\openpyxl\worksheet\worksheet.py", line 241, in cell
    if row < 1 or column < 1:
       ^^^^^^^
TypeError: '<' not supported between instances of 'builtin_function_or_method' and 'int'
2025-04-02 11:24:51,091 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:51,183 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:51,262 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:51,329 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:51,549 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:51,611 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:51,678 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:51,761 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:51,822 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:51,886 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:51,952 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:52,021 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:52,083 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:52,157 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:52,216 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:52,284 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:52,391 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:52,468 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:52,548 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:52,636 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:52,725 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:53,025 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:53,098 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:53,164 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:53,228 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:53,437 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:53,523 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:53,590 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:53,654 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:53,740 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:53,829 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:53,911 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:54,029 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:54,096 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:54,163 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:54,232 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:54,306 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:54,392 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:54,488 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:54,569 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:54,651 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:54,738 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:24:54,889 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 79, in <module>
    msg.Move(namespace.Folders[email_field].Folders['WorkOn_Processed'])
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\.venvWorkOn\Lib\site-packages\win32com\client\dynamic.py", line 317, in __getitem__
    self._oleobj_.Invoke(dispid, LCID, invkind, 1, index)
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Falha na operação tentada. Objeto não encontrado.', None, 0, -2147221233), None)
2025-04-02 11:30:47,554 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Não é possível executar a operação porque o objeto foi excluído.', None, 0, -2147221238), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 80, in <module>
    msg.save()
  File "<COMObject <unknown>>", line 2, in save
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Não é possível executar a operação porque o objeto foi excluído.', None, 0, -2147221238), None)
2025-04-02 11:30:47,714 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Não é possível executar a operação porque o objeto foi excluído.', None, 0, -2147221238), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 80, in <module>
    msg.save()
  File "<COMObject <unknown>>", line 2, in save
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Não é possível executar a operação porque o objeto foi excluído.', None, 0, -2147221238), None)
2025-04-02 11:30:47,887 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Não é possível executar a operação porque o objeto foi excluído.', None, 0, -2147221238), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 80, in <module>
    msg.save()
  File "<COMObject <unknown>>", line 2, in save
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Não é possível executar a operação porque o objeto foi excluído.', None, 0, -2147221238), None)
2025-04-02 11:30:48,228 - ERROR - Erro ao processar padrão de corpo e/ou texto do e-mail: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Não é possível executar a operação porque o objeto foi excluído.', None, 0, -2147221238), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 80, in <module>
    msg.save()
  File "<COMObject <unknown>>", line 2, in save
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Não é possível executar a operação porque o objeto foi excluído.', None, 0, -2147221238), None)
2025-04-02 11:30:48,346 - ERROR - Erro no processamento dos e-mails: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Não é possível executar a operação porque o objeto foi excluído.', None, 0, -2147221238), None)
Traceback (most recent call last):
  File "c:\Users\KRP1PO\OneDrive - Bosch Group\1.Projetos\4_RPAWorkOn\scripWorkOn.py", line 89, in <module>
    msg.save()
  File "<COMObject <unknown>>", line 2, in save
pywintypes.com_error: (-2147352567, 'Exceção.', (4096, 'Microsoft Outlook', 'Não é possível executar a operação porque o objeto foi excluído.', None, 0, -2147221238), None)
